// This code was generated by Hypar.
// Edits to this code will be overwritten the next time code generation occurs.
// DO NOT EDIT THIS FILE.
using Amazon.Lambda.Core;
using Hypar.Geometry;
using Hypar.Elements;
using Hypar.GeoJSON;
using Newtonsoft.Json;
using System.Collections.Generic;

[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]
namespace Hypar.Functions
{
	public class Function
	{
        public Dictionary<string,object> Handler(Input input, ILambdaContext context)
    	{
			var f = new HyparStarter();
			var output = f.Execute(input);
			var results = output.Model.ToHypar();
			results["computed"] = JsonConvert.SerializeObject(output);
			return results;
    	}
  	}
}