// This code was generated by Hypar.
// Edits to this code will be overwritten the next time code generation occurs.
// DO NOT EDIT THIS FILE.
using Hypar.Functions.Execution.AWS;
using Newtonsoft.Json;

namespace Hypar
{
    public class HyparInputs: S3Args
	{
		/// <summary>
		/// The amplitude in the x direction.
		/// </summary>
		[JsonProperty("X Amplitude")]
		public double XAmplitude {get;}

		/// <summary>
		/// The amplitude in the y direction.
		/// </summary>
		[JsonProperty("Y Amplitude")]
		public double YAmplitude {get;}


		
		/// <summary>
		/// Construct a HyparInputs with default inputs.
		/// This should be used only for testing.
		/// </summary>
		public HyparInputs(string executionId) : base(executionId)
		{
			this.XAmplitude = 10;
			this.YAmplitude = 10;

		}
		
		/// <summary>
		/// Construct a HyparInputs specifying all inputs.
		/// </summary>
		/// <returns></returns>
		[JsonConstructor]
		public HyparInputs(double xamplitude, double yamplitude, string executionId, string bucketName, string uploadsBucket, string gltfKey, string elementsKey, string ifcKey): base(executionId, bucketName, uploadsBucket, gltfKey, elementsKey, ifcKey)
		{
			this.XAmplitude = xamplitude;
			this.YAmplitude = yamplitude;

		}
	}
}