// This code was generated by Hypar.
// Edits to this code will be overwritten the next time code generation occurs.
// DO NOT EDIT THIS FILE.
using Hypar.Elements;
using Hypar.GeoJSON;
using Hypar.Geometry;
using Newtonsoft.Json;

namespace Hypar.Functions
{
    public class Output
    {
        /// <summary>
        /// The area of the mass.
        /// </summary>
        [JsonProperty("area")]
        public double Area { get; }


        /// <summary>
        /// The Model.
        /// For input classes, the Model will contain data computed by prior executions on Hypar.
        /// For output classes, the Model will contain data that you want to return to Hypar.
        /// </summary>
		[JsonIgnore]
        public Model Model { get; set; }

        public Output(double area)
        {
            this.Area = area;

        }
    }
}